export const config = {
  projection: "geoNaturalEarth1",
  strokeColor: "#1f2a37",
  highlightFillColor: "#d62828",
  highlightPalette: ["#d62828", "#2563eb", "#16a34a", "#f59e0b", "#9333ea", "#0f766e", "#ea580c", "#db2777"],
  labelColor: "#111111",
  labelFontSize: 9,
  capitalZoomThreshold: 5,
  capitalLabelColor: "#0f172a",
  capitalLabelFontSize: 11,
  capitalDotColor: "#111827",
  capitalDotRadius: 2.8,
  capitalLabelHaloColor: "#ffffff",
  capitalLabelHaloWidth: 2.2,
  allowedLeaderImageHosts: ["commons.wikimedia.org", "upload.wikimedia.org"],
  circleMinRadius: 4,
  circleMaxRadius: 28,
  circleOpacity: 0.35,
  circleStrokeColor: "#0b1220",
  circleStrokeWidth: 0.6,
  populationNumberLocale: "en-US",
  leaderBadgeRadius: 9,
  leaderBadgeGap: 6,
  leaderBadgeStrokeColor: "#ffffff",
  leaderBadgeStrokeWidth: 1.1,
  minZoom: 1,
  maxZoom: 8,
  zoomStep: 1.25,
  wheelZoomStep: 0.16,
  panPadding: 20,
  strokeWidth: 0.7,
  backgroundColor: "#f5f2ec",
  fitPadding: 18,
};
